/// g++ setup_plot.cpp -O3 -std=c++2a -lfmt && a.out # [this](https://fmt.dev/) is required

#include <iostream>
#include <fstream>
#include <string>
#include <fmt/core.h>

#define FILENAME "semilog.tikz"

const std::string tikzpic = R"(%%% autogenerated %%%
\begin{{tikzpicture}}
    \begin{{axis}}[
        axis line style={{draw=none}},                        %% remove axis lines
        % axis x line*=bottom, % axis y line*=left,         %% sets axis line 
        ytick distance={{5}},                                 %% sets distance between horizontal line of 5 units
        xmode=log,
        xmin=1e-2, xmax=1e{},
        ymin=-40, ymax={},
        grid=both,
        major grid style={{line width=.12pt, black!38}},
        minor grid style={{line width=.12pt, black!20}},      
        yticklabel=\empty, xticklabel=\empty,               %% remove x and y labels
    ]
    \end{{axis}}
\end{{tikzpicture}} 
)";

int writeToFile(const char* filename, const std::string content) {
    std::ofstream myfile;
    myfile.open(filename);
    myfile << content;
    myfile.close(); 
    std::cout << fmt::format("{} correctly overwritten.\n", filename);
    return 0;
}

int main() {
    int num_decades = 9;
    int num_vertical_steps = 90;

    std::cout << "num_decades? [default 9] ";
    std::cin >> num_decades;
    std::cout << "num_vertical_steps? [default 90] ";
    std::cin >> num_vertical_steps;

    std::string content = fmt::format(
                                tikzpic, 
                                num_decades-2,
                                num_vertical_steps-40
                            );
    writeToFile(FILENAME, content);

    return 0;
}
